# Server Configuration

# Network settings
network:
  ip: "0.0.0.0"
  port: 25565
velocity-secret: "test"

# Branding information
branding:
  brand-name: "<red>Powered by SLIME</red>"
  animate: false
  animation-interval: 2
  animation-styles:
    - "&c&lWelcome to &r&bSLIME"
    - "&a&lEnjoy &r&bSLIME"
    - "&e&lHave a great time with &r&bSLIME"
    - "&d&lExplore &r&bSLIME"

# Spawn settings
spawn:
  position: "100,20,100"

# Protection settings
protection:
  disable-build-protection: true
  block-break-message:
    enable: false
    message: "<red>test</red>"

# Items
server-gui-title: "<gradient:#ff007f:#7f00ff>XenooCC Server</gradient>"

compass-item:
  name: "<gradient:#ff4500:#ff7f50>Compass</gradient>"
  lore:
    - "<gradient:#00ff00:#7fff00>Navigate the world</gradient>"
    - "<gradient:#ffd700:#ff8c00>Explore and discover!</gradient>"

settings-item:
  name: "<gradient:#ff4500:#ff7f50>Settings</gradient>"
  lore:
    - "<gradient:#00bfff:#1e90ff>Customize your experience</gradient>"
    - "<gradient:#ff007f:#7f00ff>Adjust preferences</gradient>"

player-item:
  name: "<gradient:#ff4500:#ff7f50>Player Settings</gradient>"
  lore:
    - "<gradient:#00ff00:#7fff00>Manage player options</gradient>"

# MOTD
motd:
  description: "test"
  players-hidden: true

# Scoreboard
scoreboard:
  title: "<gradient:#ff007f:#7f00ff>XenooCC</gradient>"
  lines:
    - "<gray><strikethrough>                                                        </strikethrough></gray>"
    - "<gradient:#ff7f50:#ff4500>Welcome to the Lobby!</gradient>"
    - "<gradient:#00ff00:#7fff00>Online Players: <playercount></gradient>"
    - "<green>Lobby: <lobby></green>"
    - "<gradient:#00bfff:#1e90ff>Your rank: <rank></gradient>"
    - "<gradient:#ffd700:#ff8c00>Enjoy your stay!</gradient>"
    - "<gray><strikethrough>                                                        </strikethrough></gray>"

# Header & Footer
header: "<gradient:#ff007f:#7f00ff>Welcome to XenooCC!</gradient>"
footer: "<gradient:#00bfff:#1e90ff>Enjoy your stay!</gradient>"

# Chat Format
chat-format: "<prefix><name>: <message>"
group-formats:
  default: "<name>: <message>"
  owner: "<prefix> <red><name><grey> >></grey> <dark_red><message>"

# Broadcast
broadcast: "<red>[ANNUNCIO]</red> <message>"
title-settings:
  fadeIn:
    value: 2
    unit: seconds
  stay:
    value: 1
    unit: minutes
  fadeOut:
    value: 2
    unit: seconds

# MISC
deathY: 20