# Server Configuration

file-version: 1

# Network settings
network:
  ip: "0.0.0.0"
  port: 25566
  type: OFFLINE # VALUES: VELOCITY, OFFLINE, ONLINE

# Spawn settings
spawn:
  position: "100,20,100"

# Protection settings
protection:
  disable-build-protection: true
  block-break-message:
    enable: false
    message: "<red>test</red>"

# Server Links
news-link: "test"
bugs-report-link: "test"
announcement-link: "test"

# Broadcast & Title
broadcast: "<red>[ANNUNCIO]</red> <message>"
title-settings:
  fadeIn:
    value: 2
    unit: seconds
  stay:
    value: 1
    unit: minutes
  fadeOut:
    value: 2
    unit: seconds

# Item Commands
item-commands:
  minecraft:gold_block: "broadcast t"
  GOLD_INGOT: "say You clicked on a gold ingot!"
  IRON_PICKAXE: "give @p iron_pickaxe 1"

# MISC
deathY: -10
teleport-cooldown: 10