# Server Configuration

# Network settings
network:
  ip: "0.0.0.0"
  port: 25566
  type: OFFLINE # VALUES: VELOCITY, OFFLINE, ONLINE
# Branding information
branding:
  brand-name: "§cPowered by SLIME§r"
  animate: false
  animation-interval: 13
  animation-styles:
    - "§c§lWelcome to §r§bSLIME§r"
    - "§a§lEnjoy §r§bSLIME§r"
    - "§e§lHave a great time with §r§bSLIME§r"
    - "§d§lExplore §r§bSLIME§r"

# Spawn settings
spawn:
  position: "100,20,100"

# Protection settings
protection:
  disable-build-protection: true
  block-break-message:
    enable: false
    message: "<red>test</red>"

# Items
server-gui-title: "<gradient:#ff007f:#7f00ff>XenooCC Server</gradient>"
lobby-gui-title: "<red>Lobbies</red>"

compass-item:
  name: "<gradient:#ff4500:#ff7f50>Compass</gradient>"
  lore:
    - "<gradient:#00ff00:#7fff00>Navigate the world</gradient>"
    - "<gradient:#ffd700:#ff8c00>Explore and discover!</gradient>"

settings-item:
  name: "<gradient:#ff4500:#ff7f50>Settings</gradient>"
  lore:
    - "<gradient:#00bfff:#1e90ff>Customize your experience</gradient>"
    - "<gradient:#ff007f:#7f00ff>Adjust preferences</gradient>"

player-item:
  name: "<gradient:#ff4500:#ff7f50>Player Settings</gradient>"
  lore:
    - "<gradient:#00ff00:#7fff00>Manage player options</gradient>"

# Scoreboard
scoreboard:
  title: "<gradient:#ff007f:#7f00ff>XenooCC</gradient>"
  lines:
    - "<gray><strikethrough>                                                        </strikethrough></gray>"
    - "<gradient:#ff7f50:#ff4500>Welcome to the Lobby!</gradient>"
    - "<gradient:#00ff00:#7fff00>Online Players: <playercount></gradient>"
    - "<green>Lobby: <lobby></green>"
    - "<gradient:#00bfff:#1e90ff>Your rank: <rank></gradient>"
    - "<gradient:#ffd700:#ff8c00>Enjoy your stay!</gradient>"
    - "<gray><strikethrough>                                                        </strikethrough></gray>"

# Header & Footer
header:
  - "<gradient:#ff007f:#7f00ff>Welcome to XenooCC!</gradient>"
  - "test"
footer:
  - "<gradient:#00bfff:#1e90ff>Enjoy your stay!</gradient>"
  - "test"

# Chat Format
chat-format: "<lobbyid> <prefix><name>: <message>"
group-formats:
  default: "<lobbyid> <name>: <message>"
  owner: "<lobbyid> <prefix> <red><name><grey> >></grey> <dark_red><message>"

# Server Links
news-link: "test"
bugs-report-link: "test"
announcement-link: "test"

# Broadcast
broadcast: "<red>[ANNUNCIO]</red> <message>"
title-settings:
  fadeIn:
    value: 2
    unit: seconds
  stay:
    value: 1
    unit: minutes
  fadeOut:
    value: 2
    unit: seconds

# Items
item-commands:
  minecraft:gold_block: "broadcast t"
  GOLD_INGOT: "say You clicked on a gold ingot!"
  IRON_PICKAXE: "give @p iron_pickaxe 1"

# Social
socials:
  - "<red>Youtube: </red>"
  - "test"
  - "test"

# Join Items
# !! DON'T CHANGE ACTION-TAG !!
items:
  hide-item:
    material: "minecraft:gray_dye"
    slot: 2
    display-name: "Hide"
    lore:
      - "This is a hide item"
    action-tag: "hide"
  show-item:
    material: "minecraft:green_dye"
    slot: 2
    display-name: "Show"
    lore:
      - "This is a show item"
    action-tag: "show"
  compass-item:
    material: "minecraft:compass"
    slot: 4
    display-name: "<red>Compass"
    lore:
      - "select"
    action-tag: "serversl"
  lobby-item:
    material: "minecraft:nether_star"
    slot: 8
    display-name: "<red>Lobbies"
    lore:
      - "ets"
    action-tag: "lobbysl"

# MISC
deathY: 20
teleport-cooldown: 10