file-version: 1

messages:
  spawn-set: "<gradient:#00FF00:#007700>Set spawn to <pos></gradient>"
  spawn-teleport: "<gradient:#00FF00:#007700>You got teleported to spawn</gradient>"

  pet-cosmetic-created: "<gradient:#32CD32:#228B22>Successfully created pet cosmetic: <name> with entity type <entity></gradient>"
  item-cosmetic-created: "<gradient:#32CD32:#228B22>Successfully created cosmetic: <name> with item type <itemtype></gradient>"
  cosmetic-id-not-found: "<gradient:#FF0000:#AA0000>Cosmetic with ID <id> not found</gradient>"
  cosmetic-applied: "<gradient:#32CD32:#228B22>Successfully applied cosmetic: <cosmeticname></gradient>"
  cosmetic-removed: "<gradient:#FF6347:#FF4500>Successfully removed cosmetic: <cosmeticname></gradient>"

  reload: "<gradient:#00FF00:#007700>Reloaded config successfully!</gradient>"
  kick: "<gradient:#FF0000:#AA0000>Server closing...</gradient>"
  message-empty: "<gradient:#FF0000:#AA0000>Message cannot be empty.</gradient>"
  no-permission: "<gradient:#FF0000:#AA0000>You do not have permission to use this command.</gradient>"
  target-player-not-found: "<gradient:#FF0000:#AA0000>Target player not found or invalid.</gradient>"
  execute-command-message: "<gradient:#32CD32:#00FF00>Player <target> executed <command></gradient>"
  lobby-created: "<gradient:#32CD32:#00FF00>Created lobby with name <lobbyname></gradient>"

  disguise-removed: "<gradient:#32CD32:#228B22>Your disguise has been removed.</gradient>"
  not-disguised: "<gradient:#FF0000:#AA0000>You are not disguised.</gradient>"
  already-disguised: "<gradient:#FF6347:#FF4500>You are already disguised!</gradient>"
  disguise-nickname: "<gradient:#32CD32:#228B22>You are now disguised as <nickname>!</gradient>"
  disguise-entity: "<gradient:#32CD32:#228B22>You are now disguised as a <entity>!</gradient>"

  already-unvanished: "<gradient:#FF00FF:#00FFFF>You are already visible!</gradient>"
  already-vanished: "<gradient:#FFA500:#FF4500>You are already vanished!</gradient>"
  vanish: "<gradient:#00FF00:#32CD32>You are now vanished</gradient>"
  unvanish: "<gradient:#00FFFF:#1E90FF>You are now unvanished</gradient>"

  show: "<gradient:#32CD32:#00FF00>You have shown all players on the server</gradient>"
  hide: "<gradient:#FF6347:#FF4500>You have hidden all players on the server</gradient>"

  teleport-executor-message: "<gradient:#32CD32:#00FF00>Success! You have teleported <target> to your location.</gradient>"
  teleport-target-message: "<gradient:#32CD32:#00FF00>You've been summoned by <player>! Hold tight!</gradient>"
  teleport-yourself-to-yourself-error: "<gradient:#FF0000:#AA0000>Error: You can't teleport yourself to yourself!</gradient>"
  teleport-to-coordinate: "<gradient:#32CD32:#00FF00>Whoosh! You've been teleported to: <pos></gradient>"
  coordinates-out-of-bound: "<gradient:#FF0000:#AA0000>Error: The coordinates you entered are out of bounds.</gradient>"
  teleport-wait-time: "<gradient:#FF6347:#FF4500>You must wait <time> seconds before teleporting again.</gradient>"
  teleport-to-player: "<gradient:#32CD32:#00FF00>You have been teleported to <target>!</gradient>"

  hologram-line-updated: "<gradient:#32CD32:#7FFF00>Hologram line updated</gradient> at index <gradient:#EE82EE:#DA70D6><index></gradient> <gray>(ID: <id>)</gray>"
  hologram-line-removed: "<gradient:#FF6347:#FF4500>Hologram line removed</gradient> from index <gradient:#00BFFF:#1E90FF><index></gradient> <gray>(ID: <id>)</gray>"
  hologram-line-inserted: "<gradient:#FFD700:#FF8C00>Hologram line inserted</gradient> at index <gradient:#ADD8E6:#6495ED><index></gradient> <gray>(ID: <id>)</gray>"
  hologram-line-added: "<gradient:#00FF00:#00FFFF>Hologram line added successfully!</gradient> <gray>(ID: <id>)</gray>"
  hologram-created: "<gradient:#00FF00:#007700>Hologram created with ID: <id></gradient>"
  hologram-does-not-exists: "<gradient:#FF0000:#AA0000>Hologram with ID <id> does not exist.</gradient>"
  hologram-deleted: "<gradient:#FF6347:#FF4500>Hologram <id> deleted.</gradient>"
  hologram-moved: "<gradient:#32CD32:#00FF00>Hologram <id> moved to position <pos></gradient>"

  cannot-execute-console: "<gradient:#FF0000:#AA0000>You can not execute this command from console</gradient>"

  gamemode-switch: "<gradient:#32CD32:#00FF00>Switched GameMode to <gamemode></gradient>"
  gamemode-switch-other: "<gradient:#32CD32:#00FF00>Your GameMode has been switched to <gamemode></gradient>"
  gamemode-switch-other-self: "<gradient:#32CD32:#00FF00>Switched the GameMode for <target> to <gamemode></gradient>"

  lobby-not-found: "<gradient:#FF0000:#AA0000>Lobby not found!</gradient>"
  already-in-lobby: "<gradient:#FF0000:#AA0000>You are already in this lobby!</gradient>"
  failed-lobby-teleport: "<gradient:#FF6347:#FF4500>Failed to teleport. Please try again.</gradient>"
  teleport-to-lobby: "<gradient:#32CD32:#00FF00>Teleported to <lobby></gradient>"
  failed-teleport-main-lobby: "<gradient:#FF6347:#FF4500>Failed to teleport to the main lobby. Please try again.</gradient>"
  teleport-to-main-lobby: "<gradient:#32CD32:#00FF00>Teleported to the main lobby.</gradient>"
  already-in-main-lobby: "<gradient:#FF0000:#AA0000>You are already in the main lobby.</gradient>"