messages:
  spawn-set: "<gradient:#00FF00:#007700>Set spawn to <pos></gradient>"
  spawn-teleport: "<gradient:#00FF00:#007700>You got teleported to spawn</gradient>"

  pet-cosmetic-created: "<green>Successfully created pet cosmetic: <name> with entity type <entity></green>"
  item-cosmetic-created: "<green>Successfully created cosmetic: <name> with item type <itemtype></green>"
  cosmetic-id-not-found: "<red>Cosmetic with id <id> not found</red>"
  cosmetic-applied: "<green>Successfully applied cosmetic: <cosmeticname></green>"
  cosmetic-removed: "<red>Successfully removed cosmetic: <cosmeticname></red>"

  reload: "<gradient:#00FF00:#007700>Reloaded config successfully!</gradient>"
  kick: "<gradient:#FF0000:#AA0000>Server closing...</gradient>"
  message-empty: "<gradient:#FF0000:#AA0000>Message cannot be empty.</gradient>"
  no-permission: "<red>You do not have permission to use this command.</red>"
  target-player-not-found: "<red>Target player not found or invalid.</red>"
  execute-command-message: "<green>Player <target> executed <command></green>"
  lobby-created: "<green>Created lobby with name <lobbyname></green>"

  teleport-executor-message: "<green>Success! You have teleported <target> to your location.</green>"
  teleport-target-message: "<green>You've been summoned by <player>! Hold tight!</green>"
  teleport-yourself-to-yourself-error: "<red>Error: You can't teleport yourself to yourself!</red>"
  teleport-to-coordinate: "<green>Whoosh! You've been teleported to: <pos></green>"
  coordinates-out-of-bound: "<red>Error: The coordinates you entered are out of bounds.</red>"
  teleport-wait-time: "<red>You must wait <time> seconds before teleporting again.</red>"
  teleport-to-player: "<green>You have been teleported to <target>!</green>"

  hologram-created: "<gradient:#00FF00:#007700>Hologram created with ID: <id></gradient>"
  hologram-does-not-exists: "<red>Hologram with ID <id> does not exist.</red>"
  hologram-deleted: "<red>Hologram <id> deleted.</red>"
  hologram-moved: "<green>Hologram <id> moved to position <pos></green>"

  cannot-execute-console: "<gradient:#FF0000:#AA0000>You can not execute this command from console</gradient>"

  gamemode-switch: "<green>Switched GameMode to <gamemode></green>"
  gamemode-switch-other: "<green>Your GameMode has been switched to <gamemode></green>"
  gamemode-switch-other-self: "<green>Switched the GameMode for <target> to <gamemode></green>"

  lobby-not-found: "<red>Lobby not found!</red>"
  already-in-lobby: "<red>You are already in this lobby!</red>"
  failed-lobby-teleport: "<red>Failed to teleport. Please try again.</red>"
  teleport-to-lobby: "<green>Teleported to <lobby></green>"
  failed-teleport-main-lobby: "<red>Failed to teleport to the main lobby. Please try again.</red>"
  teleport-to-main-lobby: "<green>Teleported to the main lobby.</green>"
  already-in-main-lobby: "<red>You are already in the main lobby.</red>"