messages:
  spawn-set: "<green>Set spawn to <pos></green>"
  spawn-teleport: "<green>You got teleported to spawn</green>"
  reload: "<green>Reloaded config successfully!</green>"
  kick: "<red>Server closing...</red>"
  message-empty: "<red>Message cannot be empty.</red>"
  hologram: "<green>Hologram of type <hologramtype> created!</green>"
  region-setup: "<green>Region setup started for <regionname></green>"
  region-setup-first: "<red>You need to start a region setup first using /region create (regionName).</red>"
  cannot-execute-console: "<red>Cannot execute from console</red>"

titles:
  title: "test"
  subtitle: "test <regionname>"