messages:
  spawn-set: "<gradient:#00FF00:#007700>Set spawn to <pos></gradient>"
  spawn-teleport: "<gradient:#00FF00:#007700>You got teleported to spawn</gradient>"

  reload: "<gradient:#00FF00:#007700>Reloaded config successfully!</gradient>"
  kick: "<gradient:#FF0000:#AA0000>Server closing...</gradient>"
  message-empty: "<gradient:#FF0000:#AA0000>Message cannot be empty.</gradient>"
  hologram: "<gradient:#00FF00:#007700>Hologram of type <hologramtype> created!</gradient>"

  cannot-execute-console: "<gradient:#FF0000:#AA0000>You can not execute this command from console</gradient>"

  gamemode-switch: "<green>Switched GameMode to <gamemode></green>"
  gamemode-switch-other: "<green>Your GameMode has been switched to <gamemode></green>"
  gamemode-switch-other-self: "<green>Switched the GameMode for <target> to <gamemode></green>"